server:
  port: 8082



spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes[0]:
        id: users-status-check
        uri: lb://demo-resource-server
        predicates[0]: Path=/users/**, /token/**, /student/**
        predicates[1]: Method=GET
        filters[0]: RemoveRequestHeader=Cookie

      routes[1]:
        id: albums
        uri: lb://albums-resource-server
        predicates[0]: Path=/albums
        predicates[1]: Method=GET
        filters[0]: RemoveRequestHeader=Cookie

      routes[2]:
        id: photos
        uri: lb://photos-resource-server
        predicates[0]: Path=/photos
        predicates[1]: Method=GET
        filters[0]: RemoveRequestHeader=Cookie

      routes[3]:
        id: flask
        uri: lb://data-aggregation-service
        predicates[0]: Path=/student/**
        predicates[1]: Method=POST
        filters[0]: RemoveRequestHeader=Cookie

  application:
    name: api-gateway
  # registering with eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


